### ISSUE TITLE
OpenCR Docker Image Size

### ISSUE THREAD

**Issue by MattyJ007** [intrahealth/client-registry#12]
# 5.21GB Image!

I've downloaded the OpenCR image from dockerhub `docker pull intrahealth/opencr` and the download was over 2GB. Unpacked this turns into a 5GB image.
This image size does not make sense especially after looking at the `Dockerfile` located in `/docker/opencr/Dockerfile`.

Why is the image so large?

**Comment by citizenrich** [comment]
That is indeed a crazy size. I'll have a look.

**Comment by citizenrich** [comment]
Yeah, so my leaving in a 4+GB .vagrant VM and using COPY in the Dockerfile works wonders on increasing image size. I'll revise the Dockerfile to use git clone. Will update the issue when I get it done.

**Comment by citizenrich** [comment]
https://github.com/intrahealth/client-registry/commit/79d5eb3d5b70704bd7de5c0e81c7c0ac72829cef

**Comment by citizenrich** [comment]
The image size is down to 162MB. Pushed latest to: https://hub.docker.com/repository/docker/intrahealth/opencr/tags

Note that the cicd docker-compose fails (OpenCR exits) because ES and HAPI aren't up when OpenCR is looking for its backends. This requires a wait-for-it script or similar. TBD.

**Comment by MattyJ007** [comment]
4+GB of vagrant does sound excessive :laughing: 
I pulled the new image and tested with the bulk import! All working perfectly with our demo scripts :tada: 
Thanks Richard!

**Comment by citizenrich** [comment]
Thanks. I'll close the issue.
