### ISSUE TITLE
Inconsistent FHIR API endpoints

### ISSUE THREAD

**Issue by rcrichton** [intrahealth/client-registry#16]
There are a number of API endpoints that are based on FHIR yet there are some inconsistencies in the urls used. The base url keeps changing. E.g.:

```
/Patient
/
/fhir/:resource?/:id?
/ocrux/fhir/:resource?/:id?
```

**Comment by ashaban** [comment]
/Patient and / are currently deprecated. submitting patients should now be done with /fhir for patients bundle or /fhir/Patient for a single Patient
