### ISSUE TITLE
Does mediator matching only consider the first 3000 records?

### ISSUE THREAD

**Issue by rcrichton** [intrahealth/client-registry#17]
It appears that the mediator matching may be restricted to only matching against the first 3000 records. Is this the intention? If so it would be clearly outlined int eh docs.

See https://github.com/intrahealth/client-registry/blob/master/server/lib/medMatching.js#L27

**Comment by ashaban** [comment]
@rcrichton it pulls the first 3000 records, then it uses the next url to process others.
@rcrichton i do recommend that you use the ESMatching, we deprecated the mediator matching and it is missing a lot of features like probability matching etc.
