### ISSUE TITLE
Pagination on patients list appears to be broken

### ISSUE THREAD

**Issue by rcrichton** [intrahealth/client-registry#20]
I get a loader that never resolves and it looks like to url used for pages other than 1 is incorrect: `http://localhost:8080/hapi-fhir-jpaserver/fhir?_getpages=c44d39e9-d981-41d3-a8db-b2eb1e5daaff&_getpagesoffset=10&_count=10&_pretty=true&_bundletype=searchset`

**Comment by rcrichton** [comment]
Any comment on this @ashaban I've run into this again on a newer setup.

**Comment by ashaban** [comment]
@rcrichton this issues is fixed. You may need to hot reload the browser for the changes to take effect.
