### ISSUE TITLE
Create a new user

### ISSUE THREAD

**Issue by mugootugoo** [intrahealth/client-registry#22]
The system is not allowing for the creation of a new user, when logged in as root@intrahealth.org. For example, if I wanted to create the user 'rahul' with my own password, I am able to enter the information in the "new user" fields, but it does not 'save'.

**Comment by citizenrich** [comment]
@ashaban Can you have a look?

**Comment by ashaban** [comment]
@mugootugoo reopen this issue if you still have this problem
