### ISSUE TITLE
Feature request: 'm' and 'u' values for probablistic matching

### ISSUE THREAD

**Issue by mugootugoo** [intrahealth/client-registry#26]
How to select 'm' and 'u' values, if the feature is supported?

**Comment by citizenrich** [comment]
These are entered into the decision rules config file. They must be known beforehand. 

Determining the proper values are left to the administrator of the system, but generally you'd need to explore what makes sense for your use case, minimum data set, and sample of the data to be matched. It's a statistical exercise that must be done externally.

There's interest on the part of the maintainers to make trying different values of these a feature within the system itself in the future. If you're interested in that let us know.
