### ISSUE TITLE
Can't login to CRUX I get "Token is missing" error 

### ISSUE THREAD

**Issue by logicsandeep** [intrahealth/client-registry#29]
I installed the FHIR and Elastic search via docker container and also following all the steps from the document below and yet when I try to login with the user/password provided in the documentation I get "Token is missing" error in the console.

**Documentation reference link:**
https://intrahealth.github.io/client-registry/dev/docker/

**Comment by ashaban** [comment]
@logicsandeep i had to rebuild the frontend, it was using old files which were referencing wrong authentication endpoint. You will need to update your app to get the new changes. Feel free to open this issue if you will still have problems with login

**Comment by logicsandeep** [comment]
Sure @ashaban . Thanks for fixing the issue. I'll get your changes today. Have you also fixed the URLs for getClients and getURI API calls too? It should have been /config/getClients.
