### ISSUE TITLE
Crux application does not show the patients 

### ISSUE THREAD

**Issue by logicsandeep** [intrahealth/client-registry#31]
I'm using HAPI FHIR version 5.1 and I cloned the client-registry repo sometime in the last 2 weeks. I'm able to verify that the API from HAPI FHIR returns the list of patients but they are not rendered in the CRUX application.
<img width="1393" alt="Screen Shot 2020-10-12 at 6 55 20 AM" src="https://user-images.githubusercontent.com/4108057/95738871-ec3c6080-0c57-11eb-9999-33dcd713cc4c.png">

**Comment by logicsandeep** [comment]
Can you please provide me access to push? I've found a solution to this issue and I've created a local branch but I don't have access to push my changes.

**Comment by lduncan-intrah** [comment]
You should be able to do a pull request and we can the incorporate the change.

Thanks!

**Comment by logicsandeep** [comment]
This issue can be closed. We need to create the patient the OCR service to see them in CRUX. I was able to create the patients successfully and the patients showed up in CRUX.
