### ISSUE TITLE
Does Open CR work with AWS Elastic search?

### ISSUE THREAD

**Issue by logicsandeep** [intrahealth/client-registry#33]
Has anybody tried setting up your software with AWS Elastic search? Elastic search installation involves 2 custom plugins.

1) phonetic analysis = Already available in AWS ES 7.5 
2) https://github.com/intrahealth/similarity-scoring, has anybody tried installing the similarity scoring into AWS Elastic search?

I just want to understand can your software work with AWS Elastic search and if yes, how to solve point# 2 above.

**Comment by lduncan-intrah** [comment]
From what I've been able to find, AWS doesn't allow custom plugins to be installed so it would not work.

According to this https://www.elastic.co/guide/en/cloud/current/ec-adding-elastic-plugins.html some levels of the Elastic Cloud do allow uploading plugins so that could be used.

**Comment by logicsandeep** [comment]
Thank you so much for a quick reply.
