### ISSUE TITLE
UID Edge Case #3 - Orphaned UID

### ISSUE THREAD

**Issue by emilygeorge00** [intrahealth/client-registry#4]
UID1 contains records A&B
UID2 contains record C
Record B is unlinked from UID1 and is associated to UID2
Record A is linked to UID3, leaving UID1 empty
What becomes of UID1?
Should it be marked as ‘inactive’ and now point to UID3?
Should it be deleted?

**Comment by ashaban** [comment]
UID1 will be linked to UID3 using replaced-by
