### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by wluyima** [intrahealth/client-registry#67]
It would be nice if we can have the following improvements,

- Display death information i.e. in case the patient is deceased, show it and in case the death date is specified display it
- Display the patient's addresses if specified
- Display the fact that a patient is marked as inactive
- When displaying telecom fields like phone number, display the **use** field value in case it is specified i.e. home vs mobile

**Comment by citizenrich** [comment]
Thanks for the great feedback. @ashaban

**Comment by ashaban** [comment]
Fixed. You should now be able to tell opencr the fields to be displayed on the search patient report, this includes search filters as well. here is where you define them https://github.com/intrahealth/client-registry/blob/master/resources/Relationships/PatientDisplay.json
