### ISSUE TITLE
Limit the number of items to be displayed on the action required tab

### ISSUE THREAD

**Issue by wluyima** [intrahealth/client-registry#92]
For some implementations, it is possible to have very many potential matches that need to be reviewed. Unfortunately, the action required tab takes a very long time to load the potential matches if there are many.

In my opinion, it is unnecessary to load all potential matches in the UI, it would be nice to provide a configuration property to set the maximum number of potential matches to be displayed to improve the user experience.

**Comment by citizenrich** [comment]
@ashaban

**Comment by ashaban** [comment]
this is fixed

**Comment by wluyima** [comment]
Thanks @ashaban !
